Portfolio - Mobile View
aamirkhan2478/portfolio-project pull request #3
Opened 2022-07-05 17:49 UTC by aamirkhan2478

# My Portfolio

> In this pull request I added the contact form section and footer section and completed my mobile view version successfully. In future, I will be using this website for my portfolio.

### Built With
- HTML
- CSS

2022-07-05 18:36 UTC, Ginohmk requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- No linter errors :+1: 
- Good commit messages :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 18:36 UTC, Ginohmk commented on index.html
> +          minlength="30"
- PLease from the requirements the length of a name should have a max length of 30, please insert the correct fix

2022-07-05 18:36 UTC, Ginohmk commented on index.html
> +          minlength="500"
- PLease from the requirements the length of a Textarea field  should have a max length of 500, please insert the correct fix

2022-07-05 18:36 UTC, Ginohmk commented on index.html
> +          placeholder="Full Name"
- Please  your Form should use the action and method attribute to integrate with [formspree](https://formspree.io/html)
  -  action` value should be similar to `https://formspree.io/f/{form_id}`
  - method` value equals `POST`

2022-07-05 18:36 UTC, Ginohmk commented on index.html
> +          required
- Please your webpage is not looking like that of the Figma design, please try to use the proper colors and with on all input forms and Textarea field.
- Please work on the social media icon on your design to be the same as the Figma design and also do not forget to add the dark dash on the footer section.

##### Your design 
![Screenshot from 2022-07-05 19-17-30](https://user-images.githubusercontent.com/58771507/177392114-db12504f-c4b1-4324-81da-2f78e6cb135b.png)

##### Figma design 

![Screenshot from 2022-07-05 19-31-56](https://user-images.githubusercontent.com/58771507/177392878-2f34059b-5282-45d1-81a5-3ec5fa54253e.png)

2022-07-06 08:14 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi Team 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great work on making the changes requested by the previous reviewer ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 08:14 UTC, Bondok6 commented on index.html
> +        ></textarea>
- [OPTIONAL] I suggest adding the `required` attribute in the `<textarea>` to prevent the user from sending an empty message 👌

2022-07-06 08:14 UTC, Bondok6 commented on index.html
> +      </form>
- [OPTIONAL] when I tried to submit the form I got this screen, so kindly make sure to add the `name` attribute in all your form elements to work as expected. 💯

![image](https://user-images.githubusercontent.com/45231276/177502536-aca727f5-06cb-43bc-8063-a1f63f9321dc.png)

2022-07-06 08:31 UTC, merged